server:
  port: 5432

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always



spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: zuul-server


resilience4j:
  circuitbreaker:
    instances:
      service1:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
  #        ignoreExceptions:
  #          - io.github.resilience4j.circuitbreaker.IgnoredException

  ratelimiter:
    instances:
      service1:
        limitForPeriod: 10
        limitRefreshPeriod: 100000
        timeoutDuration: 1000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

zuul:
  routes:
    add-service:
      path: "/addService/**"
      serviceId: add-service
      stripPrefix: true

    buying-and-payment-service:
      path: "/buyingAndPaymentService/**"
      serviceId: buying-and-payment-service
      stripPrefix: true

    search-service:
      path: "/searchService/**"
      serviceId: search-service
      stripPrefix: true

    order-tracking-service:
      path: "/orderTrackingService/**"
      serviceId: order-tracking-service
      stripPrefix: true

  host:
    connect-timeout-millis: 500000
    socket-timeout-millis: 5000000
  
